### ISSUE TITLE
Breaks tinymce in compose window

### ISSUE THREAD

**Issue by ghost** [mkrauser/roundcube_image_paster#1]
Installed the latest version via composer in my Kolab 3.4 installation (RC 1.1.3). After that my compose window didn't show TinyMCE anymore, all buttons for sending etc. were disabled and the window effectively unusable.
Apache and Roundcube logs were empty, but Chrome console told me the following:

Uncaught TypeError: Cannot read property 'add' of undefined                    image_paster.js:19

Disabling your plugin restores functionality

**Comment by mkrauser** [comment]
Thank you very much for reporting the issue.
RC 1.1.3 was the first version to use TinyMCE 4.1, I upgraded my code to work with that.

fixed in https://github.com/mkrauser/roundcube_image_paster/commit/53db8d0de4ff3d55e484ae4aa124a94039cad033

One more thing:
Updating the plugin in the RC plugin repository (https://plugins.roundcube.net) does not work right now. So you have to install the version manually for now.
